### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AestheticalZ** [AestheticalZ/FlagPFP#1]
- [x] Add scaling options to the inner image to avoid cropping.
- [x] Add custom flag definitions through JSON or XML.
- [x] Clean up the code (Max priority)
- [x] Post build event to copy all DLLs to lib folder.
